// Auto-generated by wcc build — Vue component stubs
// Import these in your Vue SFC for type safety and IDE support.

export const WccCard = 'wcc-card';
export const WccCounter = 'wcc-counter';
export const WccList = 'wcc-list';
