// Auto-generated by wcc build — React component types

export declare const WccCard: string & {
  __tag: 'wcc-card';
  Header: string;
  Footer: string;
};

export declare const WccCounter: string & {
  __tag: 'wcc-counter';

};

export declare const WccList: string & {
  __tag: 'wcc-list';

};

export declare const WccParent: string & {
  __tag: 'wcc-parent';

};

export declare const WccWrapper: string & {
  __tag: 'wcc-wrapper';

};

export declare const WccConditional: string & {
  __tag: 'wcc-conditional';

};

export declare const WccInput: string & {
  __tag: 'wcc-input';

};

export declare const WccStyled: string & {
  __tag: 'wcc-styled';

};

export declare const WccToggle: string & {
  __tag: 'wcc-toggle';

};

