// Auto-generated by wcc build — React component stubs
// Import these in your JSX. The wccReactPlugin transforms them at build time.

export const WccCard = Object.assign('wcc-card', { __tag: 'wcc-card', Header: 'header', Footer: 'footer' });
export const WccCounter = Object.assign('wcc-counter', { __tag: 'wcc-counter' });
export const WccList = Object.assign('wcc-list', { __tag: 'wcc-list' });
