// Auto-generated by wcc build — Vue component types
// Include this file in your tsconfig.json for Volar autocompletion.

export declare const WccCard: 'wcc-card';
/** Component: wcc-card */
export interface WccCardSlots {
    'header': any;
    'footer': any;
}

export declare const WccCounter: 'wcc-counter';
/** Component: wcc-counter */
export interface WccCounterProps {
    label?: string;
}
export interface WccCounterEvents {
    'count-changed': CustomEvent;
}
export interface WccCounterModels {
    'count': any;
}

export declare const WccList: 'wcc-list';
/** Component: wcc-list */

// ── Volar Global Component Types ──────────────────────────────────
// Add this file to tsconfig.json "include" for template autocompletion.

declare module 'vue' {
  export interface GlobalComponents {
    'wcc-card': new () => { $props: {} };
    'wcc-counter': new () => { $props: { label?: string; count?: any }; $emit: { (e: 'count-changed', value: any): void; (e: 'count-changed', value: any): void } };
    'wcc-list': new () => { $props: {} };
  }
}

export {}
