// Auto-generated by wcc build — React component types

export declare const WccCard: string & {
  __tag: 'wcc-card';
  Header: string;
  Footer: string;
};

export declare const WccCounter: string & {
  __tag: 'wcc-counter';

};

export declare const WccList: string & {
  __tag: 'wcc-list';

};

