/**
 * Angular adapter for WCC custom elements.
 *
 * @module @sprlab/wccompiler/adapters/angular
 *
 * ANGULAR INTEGRATION:
 *
 * 1. For basic two-way binding with [(prop)]:
 *    No adapter needed! WCC components emit propNameChange directly.
 *    Just add CUSTOM_ELEMENTS_SCHEMA to your component.
 *
 * 2. For slots (named + scoped):
 *    Copy `adapters/angular.ts` to your Angular project's src/ directory.
 *    This is the standard pattern for Web Component libraries in Angular
 *    (same as Shoelace, Lit, FAST, etc.) because Angular AOT requires
 *    directives to be compiled within the project.
 *
 *    Steps:
 *    a) Copy adapters/angular.ts → src/directives/wcc-slots.directive.ts
 *    b) Import in your component:
 *       import { WccSlotsDirective, WccSlotDef } from './directives/wcc-slots.directive';
 *    c) Add to imports: @Component({ imports: [WccSlotsDirective, WccSlotDef] })
 *    d) Add wccSlots attribute to WCC elements that use slots:
 *       <wcc-card wccSlots>
 *         <ng-template slot="header">...</ng-template>
 *       </wcc-card>
 *
 * WHY can't we distribute as a compiled package?
 *    Angular AOT requires decorator metadata that can only be generated by
 *    ng-packagr or the Angular compiler. Standard tsc output doesn't include
 *    the Ivy metadata Angular needs. A future version may provide a separate
 *    @sprlab/wccompiler-angular package compiled with ng-packagr.
 *
 * SELECTOR:
 *    The directive uses [wccSlots] attribute selector (not a dynamic exclusion
 *    selector) because Angular AOT cannot evaluate computed expressions in
 *    decorator metadata.
 */

// This file is intentionally a documentation-only .js file.
// The actual directive source is in adapters/angular.ts (TypeScript).
// Users copy it to their Angular project for AOT compilation.
