/**
 * WCC Component Types for Vue (auto-generated by wcc build).
 *
 * Provides:
 *   - Prop autocompletion in <template>
 *   - Type-checking for prop values
 *   - Event type information on hover
 */

declare module 'vue' {
  export interface GlobalComponents {
    'wcc-counter': new () => {
      $props: {
        /** Label text displayed next to the count */
        label?: string
        /** Count value (two-way bindable via v-model:count) */
        count?: number
      }
      $emit: {
        (e: 'count-changed', value: number): void
        (e: 'wcc:model', detail: { prop: string; value: any; oldValue: any }): void
      }
    }
    'wcc-card': new () => {
      $props: {}
      $emit: {}
    }
    'wcc-list': new () => {
      $props: {}
      $emit: {}
    }
  }
}

export {}
