// Auto-generated by wcc build — Vue component stubs
// Import these in your Vue SFC for type safety and IDE support.

export const WccCard = 'wcc-card';
export const WccCounter = 'wcc-counter';
export const WccList = 'wcc-list';
export const WccParent = 'wcc-parent';
export const WccWrapper = 'wcc-wrapper';
export const WccConditional = 'wcc-conditional';
export const WccInput = 'wcc-input';
export const WccStyled = 'wcc-styled';
export const WccToggle = 'wcc-toggle';
